### ISSUE TITLE
first day pisciners can be deleted

### ISSUE THREAD

**Issue by Gotr-byte** [hivehelsinki/home-cleaner#2]
People who have never logged out before (first day pisciners, chads that don't log out ) are found to not have any locations statistics thus getting deleted.

**Comment by jgengo** [comment]
Hey @Gotr-byte 

Thanks for sharing your concern, and helping us on improving our service.

This should not happen, you can see at the following line [main.py#54](https://github.com/hivehelsinki/home-cleaner/blob/ca6d8c4ab5c746ea6d334e05fd36ba8b8eff3112/app/main.py#L54) that we are checking that the users were not created within the range (default 3 months).

Let me know if you've another opinion on that and if it's fine by you that I close that issue.

**Comment by Gotr-byte** [comment]
We had a test run during the first day of the piscine and listed a pisciner user who has not logged out yet. Commented out the parts of the code which deleted user homes. Will look further into the matter.

**Comment by jgengo** [comment]
Please, feel free to reach out to me on 42world and provide me please:
- login of your user
- the value of `inactive_duration_in_months:` you setup in your config.yml
- and the exact date you ran the script

I suspect that your month setting is too short, or that you create your piscine's user way in advance compared to us.

**Comment by jgengo** [comment]
To be fixed: [PR 3](https://github.com/hivehelsinki/home-cleaner/pull/3)

Thanks for your report!
